/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visual;

/**
 *
 * @author gustavo
 */
public class TelaMateria extends javax.swing.JFrame {

  
    public TelaMateria() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotaoSalvar4 = new javax.swing.JButton();
        PainelPrincipal = new javax.swing.JPanel();
        PainelTela = new javax.swing.JPanel();
        CampoUsuarioTelaLogin3 = new javax.swing.JTextField();
        PainelTela1 = new javax.swing.JPanel();
        PainelRoxoParteCima1 = new javax.swing.JPanel();
        imagemLogoBrancaTelaMateria = new javax.swing.JLabel();
        textoNomeEmpresaTelaMateria = new javax.swing.JLabel();
        subtituloEmpresaTelaMateria = new javax.swing.JLabel();
        botaoSairTelaMateria = new javax.swing.JLabel();
        TituloCurso = new javax.swing.JLabel();
        CampoUsuarioTelaLogin4 = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        TituloMateria = new javax.swing.JLabel();
        CampoMateria = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        TituloPeriodo = new javax.swing.JLabel();
        CampoPeriodo = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        TituloCargaHoraria = new javax.swing.JLabel();
        CampoCargaHoraria = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        CampoSemestre = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        TituloSemestre = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BotaoSalvar1 = new javax.swing.JButton();
        BotaoSalvar2 = new javax.swing.JButton();
        BotaoSalvar3 = new javax.swing.JButton();
        BotaoSalvar5 = new javax.swing.JButton();

        BotaoSalvar4.setBackground(new java.awt.Color(153, 51, 255));
        BotaoSalvar4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BotaoSalvar4.setForeground(new java.awt.Color(153, 51, 255));
        BotaoSalvar4.setText("Salvar");
        BotaoSalvar4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 255)));
        BotaoSalvar4.setContentAreaFilled(false);
        BotaoSalvar4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        PainelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PainelTela.setBackground(new java.awt.Color(255, 255, 255));

        CampoUsuarioTelaLogin3.setBackground(new java.awt.Color(255, 255, 255));
        CampoUsuarioTelaLogin3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CampoUsuarioTelaLogin3.setForeground(new java.awt.Color(0, 0, 0));
        CampoUsuarioTelaLogin3.setBorder(null);

        PainelTela1.setBackground(new java.awt.Color(255, 255, 255));

        PainelRoxoParteCima1.setBackground(new java.awt.Color(153, 51, 255));

        imagemLogoBrancaTelaMateria.setBackground(new java.awt.Color(255, 255, 255));
        imagemLogoBrancaTelaMateria.setForeground(new java.awt.Color(255, 255, 255));
        imagemLogoBrancaTelaMateria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/imagemLogoBrancaTelaInicial.png"))); // NOI18N

        textoNomeEmpresaTelaMateria.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        textoNomeEmpresaTelaMateria.setForeground(new java.awt.Color(255, 255, 255));
        textoNomeEmpresaTelaMateria.setText("Cloud Minds Technologies");

        subtituloEmpresaTelaMateria.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        subtituloEmpresaTelaMateria.setForeground(new java.awt.Color(204, 204, 204));
        subtituloEmpresaTelaMateria.setText("Construindo pontes para o futuro digital");

        botaoSairTelaMateria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ImagemBotaoFecharTelaLogin.png"))); // NOI18N
        botaoSairTelaMateria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoSairTelaMateria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoSairTelaMateriaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PainelRoxoParteCima1Layout = new javax.swing.GroupLayout(PainelRoxoParteCima1);
        PainelRoxoParteCima1.setLayout(PainelRoxoParteCima1Layout);
        PainelRoxoParteCima1Layout.setHorizontalGroup(
            PainelRoxoParteCima1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelRoxoParteCima1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(imagemLogoBrancaTelaMateria)
                .addGroup(PainelRoxoParteCima1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelRoxoParteCima1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PainelRoxoParteCima1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(subtituloEmpresaTelaMateria)
                            .addComponent(textoNomeEmpresaTelaMateria))
                        .addContainerGap(484, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelRoxoParteCima1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoSairTelaMateria)
                        .addGap(20, 20, 20))))
        );
        PainelRoxoParteCima1Layout.setVerticalGroup(
            PainelRoxoParteCima1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelRoxoParteCima1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(botaoSairTelaMateria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(textoNomeEmpresaTelaMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subtituloEmpresaTelaMateria)
                .addGap(67, 67, 67))
            .addGroup(PainelRoxoParteCima1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(imagemLogoBrancaTelaMateria)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TituloCurso.setBackground(new java.awt.Color(153, 51, 255));
        TituloCurso.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TituloCurso.setForeground(new java.awt.Color(153, 51, 255));
        TituloCurso.setText("Curso");

        CampoUsuarioTelaLogin4.setBackground(new java.awt.Color(255, 255, 255));
        CampoUsuarioTelaLogin4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CampoUsuarioTelaLogin4.setForeground(new java.awt.Color(0, 0, 0));
        CampoUsuarioTelaLogin4.setBorder(null);

        jSeparator5.setBackground(new java.awt.Color(153, 51, 255));
        jSeparator5.setForeground(new java.awt.Color(153, 51, 255));

        TituloMateria.setBackground(new java.awt.Color(153, 51, 255));
        TituloMateria.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TituloMateria.setForeground(new java.awt.Color(153, 51, 255));
        TituloMateria.setText("Matéria");

        CampoMateria.setBackground(new java.awt.Color(255, 255, 255));
        CampoMateria.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CampoMateria.setForeground(new java.awt.Color(0, 0, 0));
        CampoMateria.setBorder(null);

        jSeparator6.setBackground(new java.awt.Color(153, 51, 255));
        jSeparator6.setForeground(new java.awt.Color(153, 51, 255));

        TituloPeriodo.setBackground(new java.awt.Color(153, 51, 255));
        TituloPeriodo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TituloPeriodo.setForeground(new java.awt.Color(153, 51, 255));
        TituloPeriodo.setText("Período");

        CampoPeriodo.setBackground(new java.awt.Color(255, 255, 255));
        CampoPeriodo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CampoPeriodo.setForeground(new java.awt.Color(0, 0, 0));
        CampoPeriodo.setBorder(null);

        jSeparator7.setBackground(new java.awt.Color(153, 51, 255));
        jSeparator7.setForeground(new java.awt.Color(153, 51, 255));

        TituloCargaHoraria.setBackground(new java.awt.Color(153, 51, 255));
        TituloCargaHoraria.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TituloCargaHoraria.setForeground(new java.awt.Color(153, 51, 255));
        TituloCargaHoraria.setText("Carga Horária");

        CampoCargaHoraria.setBackground(new java.awt.Color(255, 255, 255));
        CampoCargaHoraria.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CampoCargaHoraria.setForeground(new java.awt.Color(0, 0, 0));
        CampoCargaHoraria.setBorder(null);

        jSeparator8.setBackground(new java.awt.Color(153, 51, 255));
        jSeparator8.setForeground(new java.awt.Color(153, 51, 255));

        CampoSemestre.setBackground(new java.awt.Color(255, 255, 255));
        CampoSemestre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CampoSemestre.setForeground(new java.awt.Color(0, 0, 0));
        CampoSemestre.setBorder(null);

        jSeparator9.setBackground(new java.awt.Color(153, 51, 255));
        jSeparator9.setForeground(new java.awt.Color(153, 51, 255));

        TituloSemestre.setBackground(new java.awt.Color(153, 51, 255));
        TituloSemestre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TituloSemestre.setForeground(new java.awt.Color(153, 51, 255));
        TituloSemestre.setText("Semestre");

        jTable1.setBackground(new java.awt.Color(255, 255, 255));
        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 255)));
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Curso", "Matéria", "Período"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(50);
        }

        BotaoSalvar1.setBackground(new java.awt.Color(153, 51, 255));
        BotaoSalvar1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BotaoSalvar1.setForeground(new java.awt.Color(153, 51, 255));
        BotaoSalvar1.setText("Salvar");
        BotaoSalvar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 255)));
        BotaoSalvar1.setContentAreaFilled(false);
        BotaoSalvar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        BotaoSalvar2.setBackground(new java.awt.Color(153, 51, 255));
        BotaoSalvar2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BotaoSalvar2.setForeground(new java.awt.Color(153, 51, 255));
        BotaoSalvar2.setText("Editar");
        BotaoSalvar2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 255)));
        BotaoSalvar2.setContentAreaFilled(false);
        BotaoSalvar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        BotaoSalvar3.setBackground(new java.awt.Color(153, 51, 255));
        BotaoSalvar3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BotaoSalvar3.setForeground(new java.awt.Color(153, 51, 255));
        BotaoSalvar3.setText("Excluir");
        BotaoSalvar3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 255)));
        BotaoSalvar3.setContentAreaFilled(false);
        BotaoSalvar3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        BotaoSalvar5.setBackground(new java.awt.Color(153, 51, 255));
        BotaoSalvar5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BotaoSalvar5.setForeground(new java.awt.Color(153, 51, 255));
        BotaoSalvar5.setText("Limpar");
        BotaoSalvar5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 255)));
        BotaoSalvar5.setContentAreaFilled(false);
        BotaoSalvar5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout PainelTela1Layout = new javax.swing.GroupLayout(PainelTela1);
        PainelTela1.setLayout(PainelTela1Layout);
        PainelTela1Layout.setHorizontalGroup(
            PainelTela1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelTela1Layout.createSequentialGroup()
                .addComponent(PainelRoxoParteCima1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 39, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelTela1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(PainelTela1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator6)
                    .addComponent(jSeparator7)
                    .addComponent(TituloPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TituloMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TituloCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoUsuarioTelaLogin4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PainelTela1Layout.createSequentialGroup()
                        .addGroup(PainelTela1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(CampoCargaHoraria, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TituloCargaHoraria, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(40, 40, 40)
                        .addGroup(PainelTela1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TituloSemestre)
                            .addComponent(CampoSemestre, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)))
                    .addGroup(PainelTela1Layout.createSequentialGroup()
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jSeparator9))
                    .addComponent(jSeparator5)
                    .addComponent(CampoMateria)
                    .addComponent(CampoPeriodo)
                    .addComponent(BotaoSalvar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PainelTela1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelTela1Layout.createSequentialGroup()
                        .addComponent(BotaoSalvar5, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111)
                        .addComponent(BotaoSalvar2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105)
                        .addComponent(BotaoSalvar3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100))
        );
        PainelTela1Layout.setVerticalGroup(
            PainelTela1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelTela1Layout.createSequentialGroup()
                .addComponent(PainelRoxoParteCima1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(PainelTela1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PainelTela1Layout.createSequentialGroup()
                        .addComponent(TituloCurso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CampoUsuarioTelaLogin4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(TituloMateria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CampoMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(TituloPeriodo)
                        .addGap(12, 12, 12)
                        .addComponent(CampoPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addGroup(PainelTela1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TituloCargaHoraria)
                            .addComponent(TituloSemestre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PainelTela1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CampoCargaHoraria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CampoSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PainelTela1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(44, 44, 44)
                .addGroup(PainelTela1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoSalvar5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoSalvar2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoSalvar3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoSalvar1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PainelTelaLayout = new javax.swing.GroupLayout(PainelTela);
        PainelTela.setLayout(PainelTelaLayout);
        PainelTelaLayout.setHorizontalGroup(
            PainelTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelTelaLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(CampoUsuarioTelaLogin3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PainelTelaLayout.createSequentialGroup()
                .addComponent(PainelTela1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PainelTelaLayout.setVerticalGroup(
            PainelTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelTelaLayout.createSequentialGroup()
                .addComponent(PainelTela1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CampoUsuarioTelaLogin3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PainelPrincipal.add(PainelTela, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 660));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoSairTelaMateriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoSairTelaMateriaMouseClicked
        System.exit(0);
    }//GEN-LAST:event_botaoSairTelaMateriaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMateria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoSalvar1;
    private javax.swing.JButton BotaoSalvar2;
    private javax.swing.JButton BotaoSalvar3;
    private javax.swing.JButton BotaoSalvar4;
    private javax.swing.JButton BotaoSalvar5;
    private javax.swing.JTextField CampoCargaHoraria;
    private javax.swing.JTextField CampoMateria;
    private javax.swing.JTextField CampoPeriodo;
    private javax.swing.JTextField CampoSemestre;
    private javax.swing.JTextField CampoUsuarioTelaLogin3;
    private javax.swing.JTextField CampoUsuarioTelaLogin4;
    private javax.swing.JPanel PainelPrincipal;
    private javax.swing.JPanel PainelRoxoParteCima1;
    private javax.swing.JPanel PainelTela;
    private javax.swing.JPanel PainelTela1;
    private javax.swing.JLabel TituloCargaHoraria;
    private javax.swing.JLabel TituloCurso;
    private javax.swing.JLabel TituloMateria;
    private javax.swing.JLabel TituloPeriodo;
    private javax.swing.JLabel TituloSemestre;
    private javax.swing.JLabel botaoSairTelaMateria;
    private javax.swing.JLabel imagemLogoBrancaTelaMateria;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel subtituloEmpresaTelaMateria;
    private javax.swing.JLabel textoNomeEmpresaTelaMateria;
    // End of variables declaration//GEN-END:variables
}
