/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visual;

import Controller.FuncionarioController;
import Model.ModelFuncionario;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gustavo
 */
public class TelaGestao extends javax.swing.JFrame {

    ModelFuncionario modelFuncionario = new ModelFuncionario();
    FuncionarioController funcionarioController = new FuncionarioController();
    List<ModelFuncionario> listarFuncionarios = new ArrayList<>();

    public TelaGestao() {
        initComponents();
        setLocationRelativeTo(null);
        carregarFuncionarios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotaoSalvar4 = new javax.swing.JButton();
        PainelPrincipal = new javax.swing.JPanel();
        PainelTela = new javax.swing.JPanel();
        CampoUsuarioTelaLogin3 = new javax.swing.JTextField();
        PainelTela1 = new javax.swing.JPanel();
        TituloNome = new javax.swing.JLabel();
        CampoNome = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        TituloCPF = new javax.swing.JLabel();
        CampoCPF = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        TituloTelefone = new javax.swing.JLabel();
        CampoTelefone = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        TituloLogin = new javax.swing.JLabel();
        CampoLogin = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        TituloSenha = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaFuncionario = new javax.swing.JTable();
        BotaoSalvar = new javax.swing.JButton();
        BotaoEditar = new javax.swing.JButton();
        BotaoExcluir = new javax.swing.JButton();
        BotaoLimpar = new javax.swing.JButton();
        TituloEndereco = new javax.swing.JLabel();
        CampoEndereco = new javax.swing.JTextField();
        jSeparator15 = new javax.swing.JSeparator();
        TituloBairro = new javax.swing.JLabel();
        CampoBairro = new javax.swing.JTextField();
        jSeparator16 = new javax.swing.JSeparator();
        TituloComplemento = new javax.swing.JLabel();
        CampoComplemento = new javax.swing.JTextField();
        jSeparator17 = new javax.swing.JSeparator();
        TituloNumero = new javax.swing.JLabel();
        CampoNumero = new javax.swing.JTextField();
        jSeparator18 = new javax.swing.JSeparator();
        CampoSenha = new javax.swing.JPasswordField();
        PainelRoxoParteCima1 = new javax.swing.JPanel();
        BotaoVoltar = new javax.swing.JLabel();
        imagemLogoBrancaTelaInicial = new javax.swing.JLabel();
        textoNomeEmpresaTelaInicial = new javax.swing.JLabel();
        subtituloEmpresaTelaInicial = new javax.swing.JLabel();
        BotaoSair = new javax.swing.JLabel();

        BotaoSalvar4.setBackground(new java.awt.Color(153, 51, 255));
        BotaoSalvar4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BotaoSalvar4.setForeground(new java.awt.Color(153, 51, 255));
        BotaoSalvar4.setText("Salvar");
        BotaoSalvar4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 255)));
        BotaoSalvar4.setContentAreaFilled(false);
        BotaoSalvar4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        PainelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PainelTela.setBackground(new java.awt.Color(255, 255, 255));

        CampoUsuarioTelaLogin3.setBackground(new java.awt.Color(255, 255, 255));
        CampoUsuarioTelaLogin3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CampoUsuarioTelaLogin3.setForeground(new java.awt.Color(0, 0, 0));
        CampoUsuarioTelaLogin3.setBorder(null);

        PainelTela1.setBackground(new java.awt.Color(255, 255, 255));

        TituloNome.setBackground(new java.awt.Color(153, 51, 255));
        TituloNome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TituloNome.setForeground(new java.awt.Color(153, 51, 255));
        TituloNome.setText("Nome");

        CampoNome.setBackground(new java.awt.Color(255, 255, 255));
        CampoNome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CampoNome.setForeground(new java.awt.Color(153, 51, 255));
        CampoNome.setBorder(null);

        jSeparator5.setBackground(new java.awt.Color(153, 51, 255));
        jSeparator5.setForeground(new java.awt.Color(153, 51, 255));

        TituloCPF.setBackground(new java.awt.Color(153, 51, 255));
        TituloCPF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TituloCPF.setForeground(new java.awt.Color(153, 51, 255));
        TituloCPF.setText("CPF");

        CampoCPF.setBackground(new java.awt.Color(255, 255, 255));
        CampoCPF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CampoCPF.setForeground(new java.awt.Color(153, 51, 255));
        CampoCPF.setBorder(null);

        jSeparator6.setBackground(new java.awt.Color(153, 51, 255));
        jSeparator6.setForeground(new java.awt.Color(153, 51, 255));

        TituloTelefone.setBackground(new java.awt.Color(153, 51, 255));
        TituloTelefone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TituloTelefone.setForeground(new java.awt.Color(153, 51, 255));
        TituloTelefone.setText("Telefone");

        CampoTelefone.setBackground(new java.awt.Color(255, 255, 255));
        CampoTelefone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CampoTelefone.setForeground(new java.awt.Color(153, 51, 255));
        CampoTelefone.setBorder(null);

        jSeparator7.setBackground(new java.awt.Color(153, 51, 255));
        jSeparator7.setForeground(new java.awt.Color(153, 51, 255));

        TituloLogin.setBackground(new java.awt.Color(153, 51, 255));
        TituloLogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TituloLogin.setForeground(new java.awt.Color(153, 51, 255));
        TituloLogin.setText("Login");

        CampoLogin.setBackground(new java.awt.Color(255, 255, 255));
        CampoLogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CampoLogin.setForeground(new java.awt.Color(153, 51, 255));
        CampoLogin.setBorder(null);

        jSeparator8.setBackground(new java.awt.Color(153, 51, 255));
        jSeparator8.setForeground(new java.awt.Color(153, 51, 255));

        jSeparator9.setBackground(new java.awt.Color(153, 51, 255));
        jSeparator9.setForeground(new java.awt.Color(153, 51, 255));

        TituloSenha.setBackground(new java.awt.Color(153, 51, 255));
        TituloSenha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TituloSenha.setForeground(new java.awt.Color(153, 51, 255));
        TituloSenha.setText("Senha");

        TabelaFuncionario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 255)));
        TabelaFuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Login", "Senha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TabelaFuncionario);
        if (TabelaFuncionario.getColumnModel().getColumnCount() > 0) {
            TabelaFuncionario.getColumnModel().getColumn(0).setMinWidth(90);
            TabelaFuncionario.getColumnModel().getColumn(0).setPreferredWidth(90);
            TabelaFuncionario.getColumnModel().getColumn(0).setMaxWidth(90);
            TabelaFuncionario.getColumnModel().getColumn(1).setMinWidth(180);
            TabelaFuncionario.getColumnModel().getColumn(1).setPreferredWidth(180);
            TabelaFuncionario.getColumnModel().getColumn(1).setMaxWidth(180);
            TabelaFuncionario.getColumnModel().getColumn(2).setMinWidth(175);
            TabelaFuncionario.getColumnModel().getColumn(2).setPreferredWidth(175);
            TabelaFuncionario.getColumnModel().getColumn(2).setMaxWidth(175);
            TabelaFuncionario.getColumnModel().getColumn(3).setMinWidth(175);
            TabelaFuncionario.getColumnModel().getColumn(3).setPreferredWidth(175);
            TabelaFuncionario.getColumnModel().getColumn(3).setMaxWidth(175);
        }

        BotaoSalvar.setBackground(new java.awt.Color(153, 51, 255));
        BotaoSalvar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BotaoSalvar.setForeground(new java.awt.Color(153, 51, 255));
        BotaoSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/imagemBotaoSalvar.png"))); // NOI18N
        BotaoSalvar.setText("Salvar");
        BotaoSalvar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 255)));
        BotaoSalvar.setContentAreaFilled(false);
        BotaoSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSalvarActionPerformed(evt);
            }
        });

        BotaoEditar.setBackground(new java.awt.Color(153, 51, 255));
        BotaoEditar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BotaoEditar.setForeground(new java.awt.Color(153, 51, 255));
        BotaoEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/imagemBotaoEditar.png"))); // NOI18N
        BotaoEditar.setText("Editar");
        BotaoEditar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 255)));
        BotaoEditar.setContentAreaFilled(false);
        BotaoEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotaoEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotaoEditarMouseClicked(evt);
            }
        });

        BotaoExcluir.setBackground(new java.awt.Color(153, 51, 255));
        BotaoExcluir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BotaoExcluir.setForeground(new java.awt.Color(153, 51, 255));
        BotaoExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/imagemBotaoExcluir.png"))); // NOI18N
        BotaoExcluir.setText("Excluir");
        BotaoExcluir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 255)));
        BotaoExcluir.setContentAreaFilled(false);
        BotaoExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotaoExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotaoExcluirMouseClicked(evt);
            }
        });

        BotaoLimpar.setBackground(new java.awt.Color(153, 51, 255));
        BotaoLimpar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BotaoLimpar.setForeground(new java.awt.Color(153, 51, 255));
        BotaoLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/imagemBotaoLimpar.png"))); // NOI18N
        BotaoLimpar.setText("Limpar");
        BotaoLimpar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 255)));
        BotaoLimpar.setContentAreaFilled(false);
        BotaoLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotaoLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotaoLimparMouseClicked(evt);
            }
        });

        TituloEndereco.setBackground(new java.awt.Color(153, 51, 255));
        TituloEndereco.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TituloEndereco.setForeground(new java.awt.Color(153, 51, 255));
        TituloEndereco.setText("Endereço");

        CampoEndereco.setBackground(new java.awt.Color(255, 255, 255));
        CampoEndereco.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CampoEndereco.setForeground(new java.awt.Color(153, 51, 255));
        CampoEndereco.setBorder(null);

        jSeparator15.setBackground(new java.awt.Color(153, 51, 255));
        jSeparator15.setForeground(new java.awt.Color(153, 51, 255));

        TituloBairro.setBackground(new java.awt.Color(153, 51, 255));
        TituloBairro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TituloBairro.setForeground(new java.awt.Color(153, 51, 255));
        TituloBairro.setText("Bairro");

        CampoBairro.setBackground(new java.awt.Color(255, 255, 255));
        CampoBairro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CampoBairro.setForeground(new java.awt.Color(153, 51, 255));
        CampoBairro.setBorder(null);

        jSeparator16.setBackground(new java.awt.Color(153, 51, 255));
        jSeparator16.setForeground(new java.awt.Color(153, 51, 255));

        TituloComplemento.setBackground(new java.awt.Color(153, 51, 255));
        TituloComplemento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TituloComplemento.setForeground(new java.awt.Color(153, 51, 255));
        TituloComplemento.setText("Complemento");

        CampoComplemento.setBackground(new java.awt.Color(255, 255, 255));
        CampoComplemento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CampoComplemento.setForeground(new java.awt.Color(153, 51, 255));
        CampoComplemento.setBorder(null);

        jSeparator17.setBackground(new java.awt.Color(153, 51, 255));
        jSeparator17.setForeground(new java.awt.Color(153, 51, 255));

        TituloNumero.setBackground(new java.awt.Color(153, 51, 255));
        TituloNumero.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TituloNumero.setForeground(new java.awt.Color(153, 51, 255));
        TituloNumero.setText("Número");

        CampoNumero.setBackground(new java.awt.Color(255, 255, 255));
        CampoNumero.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CampoNumero.setForeground(new java.awt.Color(153, 51, 255));
        CampoNumero.setBorder(null);

        jSeparator18.setBackground(new java.awt.Color(153, 51, 255));
        jSeparator18.setForeground(new java.awt.Color(153, 51, 255));

        CampoSenha.setBackground(new java.awt.Color(255, 255, 255));
        CampoSenha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CampoSenha.setForeground(new java.awt.Color(153, 51, 255));
        CampoSenha.setBorder(null);

        javax.swing.GroupLayout PainelTela1Layout = new javax.swing.GroupLayout(PainelTela1);
        PainelTela1.setLayout(PainelTela1Layout);
        PainelTela1Layout.setHorizontalGroup(
            PainelTela1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelTela1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(PainelTela1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelTela1Layout.createSequentialGroup()
                        .addGroup(PainelTela1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator8)
                            .addComponent(TituloLogin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CampoLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addGroup(PainelTela1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelTela1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TituloSenha)
                                .addComponent(CampoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(PainelTela1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSeparator6)
                        .addComponent(jSeparator7)
                        .addComponent(TituloTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TituloNome, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CampoNome, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                        .addComponent(jSeparator5)
                        .addComponent(CampoCPF)
                        .addComponent(CampoTelefone)
                        .addComponent(TituloCPF)
                        .addComponent(BotaoSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addGroup(PainelTela1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CampoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TituloEndereco)
                    .addComponent(CampoBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TituloBairro)
                    .addComponent(CampoComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator17, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TituloComplemento)
                    .addGroup(PainelTela1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jSeparator18, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(CampoNumero, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(TituloNumero, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(PainelTela1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PainelTela1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(BotaoLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(144, 144, 144)
                        .addComponent(BotaoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotaoExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelTela1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(76, 76, 76))
        );
        PainelTela1Layout.setVerticalGroup(
            PainelTela1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelTela1Layout.createSequentialGroup()
                .addGroup(PainelTela1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelTela1Layout.createSequentialGroup()
                        .addGroup(PainelTela1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PainelTela1Layout.createSequentialGroup()
                                .addComponent(TituloEndereco)
                                .addGap(241, 241, 241)
                                .addComponent(TituloNumero)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CampoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator18, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelTela1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(TituloNome)
                        .addGap(18, 18, 18)
                        .addGroup(PainelTela1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PainelTela1Layout.createSequentialGroup()
                                .addGroup(PainelTela1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(PainelTela1Layout.createSequentialGroup()
                                        .addGroup(PainelTela1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(PainelTela1Layout.createSequentialGroup()
                                                .addComponent(CampoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(PainelTela1Layout.createSequentialGroup()
                                                .addComponent(CampoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(24, 24, 24)
                                        .addComponent(TituloCPF)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(CampoCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PainelTela1Layout.createSequentialGroup()
                                        .addComponent(TituloBairro)
                                        .addGap(18, 18, 18)
                                        .addComponent(CampoBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(24, 24, 24)
                                .addComponent(TituloTelefone)
                                .addGap(12, 12, 12)
                                .addComponent(CampoTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PainelTela1Layout.createSequentialGroup()
                                .addComponent(TituloComplemento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CampoComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator17, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(24, 24, 24)
                        .addGroup(PainelTela1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TituloLogin)
                            .addComponent(TituloSenha))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PainelTela1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CampoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CampoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PainelTela1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(PainelTela1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelTela1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(PainelTela1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BotaoLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotaoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotaoExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PainelTela1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(BotaoSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(115, Short.MAX_VALUE))
        );

        PainelRoxoParteCima1.setBackground(new java.awt.Color(153, 51, 255));

        BotaoVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BotaoVoltarBranco.png"))); // NOI18N
        BotaoVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotaoVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotaoVoltarMouseClicked(evt);
            }
        });

        imagemLogoBrancaTelaInicial.setBackground(new java.awt.Color(255, 255, 255));
        imagemLogoBrancaTelaInicial.setForeground(new java.awt.Color(255, 255, 255));
        imagemLogoBrancaTelaInicial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/imagemLogoBranca.png"))); // NOI18N

        textoNomeEmpresaTelaInicial.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        textoNomeEmpresaTelaInicial.setForeground(new java.awt.Color(255, 255, 255));
        textoNomeEmpresaTelaInicial.setText("Cloud Minds Technologies");

        subtituloEmpresaTelaInicial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        subtituloEmpresaTelaInicial.setForeground(new java.awt.Color(204, 204, 204));
        subtituloEmpresaTelaInicial.setText("Construindo pontes para o futuro digital");

        BotaoSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ImagemBotaoFechar.png"))); // NOI18N
        BotaoSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotaoSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotaoSairMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PainelRoxoParteCima1Layout = new javax.swing.GroupLayout(PainelRoxoParteCima1);
        PainelRoxoParteCima1.setLayout(PainelRoxoParteCima1Layout);
        PainelRoxoParteCima1Layout.setHorizontalGroup(
            PainelRoxoParteCima1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelRoxoParteCima1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BotaoVoltar)
                .addGap(27, 27, 27)
                .addComponent(imagemLogoBrancaTelaInicial)
                .addGroup(PainelRoxoParteCima1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelRoxoParteCima1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotaoSair)
                        .addGap(14, 14, 14))
                    .addGroup(PainelRoxoParteCima1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PainelRoxoParteCima1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(subtituloEmpresaTelaInicial)
                            .addComponent(textoNomeEmpresaTelaInicial))
                        .addContainerGap(826, Short.MAX_VALUE))))
        );
        PainelRoxoParteCima1Layout.setVerticalGroup(
            PainelRoxoParteCima1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelRoxoParteCima1Layout.createSequentialGroup()
                .addGroup(PainelRoxoParteCima1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelRoxoParteCima1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(PainelRoxoParteCima1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PainelRoxoParteCima1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(textoNomeEmpresaTelaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(subtituloEmpresaTelaInicial))
                            .addComponent(imagemLogoBrancaTelaInicial)))
                    .addGroup(PainelRoxoParteCima1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PainelRoxoParteCima1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BotaoVoltar)
                            .addComponent(BotaoSair))))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PainelTelaLayout = new javax.swing.GroupLayout(PainelTela);
        PainelTela.setLayout(PainelTelaLayout);
        PainelTelaLayout.setHorizontalGroup(
            PainelTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelTelaLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(CampoUsuarioTelaLogin3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PainelTelaLayout.createSequentialGroup()
                .addGroup(PainelTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PainelTela1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PainelRoxoParteCima1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PainelTelaLayout.setVerticalGroup(
            PainelTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelTelaLayout.createSequentialGroup()
                .addComponent(PainelRoxoParteCima1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PainelTela1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(CampoUsuarioTelaLogin3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PainelPrincipal.add(PainelTela, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1330, 660));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoSalvarActionPerformed
        if (CampoNome.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Por favor, digite o Nome!", "Erro!", JOptionPane.WARNING_MESSAGE);
        } else if (CampoCPF.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Por favor, digite o CPF!", "Erro!", JOptionPane.WARNING_MESSAGE);
        } else if (CampoTelefone.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Por favor, digite o Telefone!", "Erro!", JOptionPane.WARNING_MESSAGE);
        } else if (CampoLogin.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Por favor, digite o Login!", "Erro!", JOptionPane.WARNING_MESSAGE);
        } else if (String.valueOf(CampoSenha.getPassword()).equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Por favor, digite a Senha!", "Erro!", JOptionPane.WARNING_MESSAGE);
        } else if (CampoEndereco.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Por favor, digite o Endereço!", "Erro!", JOptionPane.WARNING_MESSAGE);
        } else if (CampoBairro.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Por favor, digite o Bairro!", "Erro!", JOptionPane.WARNING_MESSAGE);
        } else if (CampoComplemento.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Por favor, digite o Complemento!", "Erro!", JOptionPane.WARNING_MESSAGE);
        } else if (CampoNumero.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Por favor, digite o Número!", "Erro!", JOptionPane.WARNING_MESSAGE);
        } else {

            modelFuncionario = new ModelFuncionario();

            modelFuncionario.setNome(CampoNome.getText());
            modelFuncionario.setCpf(CampoCPF.getText());
            modelFuncionario.setTelefone(CampoTelefone.getText());
            modelFuncionario.setLogin(CampoLogin.getText());
            modelFuncionario.setSenha(String.valueOf(CampoSenha.getPassword()));
            modelFuncionario.setEndereco(CampoEndereco.getText());
            modelFuncionario.setBairro(CampoBairro.getText());
            modelFuncionario.setComplemento(CampoComplemento.getText());
            modelFuncionario.setNumero(Integer.parseInt(CampoNumero.getText()));

            if (funcionarioController.salvarFuncionarioController(modelFuncionario)) {
                JOptionPane.showMessageDialog(this, "Funcionário cadastrado com sucesso!", "Dados cadastrados com sucesso!", JOptionPane.INFORMATION_MESSAGE);

                limparFormulario();
                carregarFuncionarios();

            } else {
                JOptionPane.showMessageDialog(this, "Erro ao cadastrar Funcionário", "Erro!", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_BotaoSalvarActionPerformed

    private void BotaoVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoVoltarMouseClicked
        new TelaInicial().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotaoVoltarMouseClicked

    private void BotaoSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoSairMouseClicked
        System.exit(0);
    }//GEN-LAST:event_BotaoSairMouseClicked

    private void BotaoLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoLimparMouseClicked
        limparFormulario();
    }//GEN-LAST:event_BotaoLimparMouseClicked

    /**
     * Realiza uma Exclusão Lógica de um Funcionário do Banco de Dados,
     * mudando o seu Status de Ativo para Excluído.
     * @param evt
     */
    private void BotaoExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoExcluirMouseClicked
        int linha = TabelaFuncionario.getSelectedRow();

        if (linha < 0) {
            JOptionPane.showMessageDialog(this, "Para excluir um Funcionário, você precisa selecionar uma linha!", "Erro ao Excluir um Funcionário!", JOptionPane.ERROR_MESSAGE);
        } else {
            int codigo = (int) TabelaFuncionario.getValueAt(linha, 0);
            if (funcionarioController.excluirFuncionario(codigo)) {
                carregarFuncionarios();
                limparFormulario();
                JOptionPane.showMessageDialog(this, "Funcionário excluído com sucesso!", "Sucesso!", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao excluir Funcionário", "Erro!", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_BotaoExcluirMouseClicked

    /**
     * Editar Funcionário no Banco de Dados pelo ID
     * @param evt 
     */
    private void BotaoEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoEditarMouseClicked
        modelFuncionario = new ModelFuncionario();
    
    int linha = TabelaFuncionario.getSelectedRow();

    if (linha < 0) {
        JOptionPane.showMessageDialog(this, "Para editar um Funcionário, você precisa selecionar uma linha!", "Erro ao Editar um Funcionário!", JOptionPane.ERROR_MESSAGE);
    } else {
        int codigo = (int) TabelaFuncionario.getValueAt(linha, 0);
        modelFuncionario = funcionarioController.editarFuncionario(codigo);
        
        CampoNome.setText(modelFuncionario.getNome());
        CampoCPF.setText(modelFuncionario.getCpf());
        CampoTelefone.setText(modelFuncionario.getTelefone());
        CampoLogin.setText(modelFuncionario.getLogin());
        CampoSenha.setText(modelFuncionario.getSenha());
        CampoEndereco.setText(modelFuncionario.getEndereco());
        CampoBairro.setText(modelFuncionario.getBairro());
        CampoComplemento.setText(modelFuncionario.getComplemento());
        CampoNumero.setText(String.valueOf(modelFuncionario.getNumero()));
        }
    }//GEN-LAST:event_BotaoEditarMouseClicked

    /**
     * Limpa os dados do Formulário
     */
    private void limparFormulario() {
        CampoNome.setText("");
        CampoCPF.setText("");
        CampoTelefone.setText("");
        CampoLogin.setText("");
        CampoSenha.setText("");
        CampoEndereco.setText("");
        CampoBairro.setText("");
        CampoComplemento.setText("");
        CampoNumero.setText("");
    }

    /**
     * Carrega uma Lista de Funcionários na Tabela
     */
    private void carregarFuncionarios() {
        listarFuncionarios = funcionarioController.listarFuncionarios();

        DefaultTableModel tabelaFuncionario = (DefaultTableModel) TabelaFuncionario.getModel();
        tabelaFuncionario.setNumRows(0);

        for (int i = 0; i < listarFuncionarios.size(); i++) {
            tabelaFuncionario.addRow(new Object[]{
                listarFuncionarios.get(i).getId(),
                listarFuncionarios.get(i).getNome(),
                listarFuncionarios.get(i).getLogin(),
                listarFuncionarios.get(i).getSenha()
            });
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGestao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGestao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGestao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGestao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaGestao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoEditar;
    private javax.swing.JButton BotaoExcluir;
    private javax.swing.JButton BotaoLimpar;
    private javax.swing.JLabel BotaoSair;
    private javax.swing.JButton BotaoSalvar;
    private javax.swing.JButton BotaoSalvar4;
    private javax.swing.JLabel BotaoVoltar;
    private javax.swing.JTextField CampoBairro;
    private javax.swing.JTextField CampoCPF;
    private javax.swing.JTextField CampoComplemento;
    private javax.swing.JTextField CampoEndereco;
    private javax.swing.JTextField CampoLogin;
    private javax.swing.JTextField CampoNome;
    private javax.swing.JTextField CampoNumero;
    private javax.swing.JPasswordField CampoSenha;
    private javax.swing.JTextField CampoTelefone;
    private javax.swing.JTextField CampoUsuarioTelaLogin3;
    private javax.swing.JPanel PainelPrincipal;
    private javax.swing.JPanel PainelRoxoParteCima1;
    private javax.swing.JPanel PainelTela;
    private javax.swing.JPanel PainelTela1;
    private javax.swing.JTable TabelaFuncionario;
    private javax.swing.JLabel TituloBairro;
    private javax.swing.JLabel TituloCPF;
    private javax.swing.JLabel TituloComplemento;
    private javax.swing.JLabel TituloEndereco;
    private javax.swing.JLabel TituloLogin;
    private javax.swing.JLabel TituloNome;
    private javax.swing.JLabel TituloNumero;
    private javax.swing.JLabel TituloSenha;
    private javax.swing.JLabel TituloTelefone;
    private javax.swing.JLabel imagemLogoBrancaTelaInicial;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel subtituloEmpresaTelaInicial;
    private javax.swing.JLabel textoNomeEmpresaTelaInicial;
    // End of variables declaration//GEN-END:variables
}
