/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visual;

/**
 *
 * @author gustavo
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicialTeste
     */
    public TelaInicial() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelPrincipal = new javax.swing.JPanel();
        PainelTela = new javax.swing.JPanel();
        PainelRoxoParteCima = new javax.swing.JPanel();
        imagemLogoBrancaTelaInicial = new javax.swing.JLabel();
        textoNomeEmpresaTelaInicial = new javax.swing.JLabel();
        subtituloEmpresaTelaInicial = new javax.swing.JLabel();
        botaoSairTelaInicial = new javax.swing.JLabel();
        PainelGrade = new javax.swing.JPanel();
        imagemGrade = new javax.swing.JLabel();
        textoImagemGradeCurricular = new javax.swing.JLabel();
        textoRestoImagemGradeCurricular = new javax.swing.JLabel();
        PainelGestao = new javax.swing.JPanel();
        imagemGestao = new javax.swing.JLabel();
        textoImagemGestao = new javax.swing.JLabel();
        PainelMateria = new javax.swing.JPanel();
        imagemMateria = new javax.swing.JLabel();
        textoImagemMateria = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        PainelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PainelTela.setBackground(new java.awt.Color(255, 255, 255));

        PainelRoxoParteCima.setBackground(new java.awt.Color(153, 51, 255));

        imagemLogoBrancaTelaInicial.setBackground(new java.awt.Color(255, 255, 255));
        imagemLogoBrancaTelaInicial.setForeground(new java.awt.Color(255, 255, 255));
        imagemLogoBrancaTelaInicial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/imagemLogoBranca.png"))); // NOI18N

        textoNomeEmpresaTelaInicial.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        textoNomeEmpresaTelaInicial.setForeground(new java.awt.Color(255, 255, 255));
        textoNomeEmpresaTelaInicial.setText("Cloud Minds Technologies");

        subtituloEmpresaTelaInicial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        subtituloEmpresaTelaInicial.setForeground(new java.awt.Color(204, 204, 204));
        subtituloEmpresaTelaInicial.setText("Construindo pontes para o futuro digital");

        botaoSairTelaInicial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ImagemBotaoFechar.png"))); // NOI18N
        botaoSairTelaInicial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoSairTelaInicial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoSairTelaInicialMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PainelRoxoParteCimaLayout = new javax.swing.GroupLayout(PainelRoxoParteCima);
        PainelRoxoParteCima.setLayout(PainelRoxoParteCimaLayout);
        PainelRoxoParteCimaLayout.setHorizontalGroup(
            PainelRoxoParteCimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelRoxoParteCimaLayout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addComponent(imagemLogoBrancaTelaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelRoxoParteCimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelRoxoParteCimaLayout.createSequentialGroup()
                        .addGroup(PainelRoxoParteCimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoNomeEmpresaTelaInicial)
                            .addComponent(subtituloEmpresaTelaInicial))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelRoxoParteCimaLayout.createSequentialGroup()
                        .addGap(700, 700, 700)
                        .addComponent(botaoSairTelaInicial)
                        .addContainerGap())))
        );
        PainelRoxoParteCimaLayout.setVerticalGroup(
            PainelRoxoParteCimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelRoxoParteCimaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botaoSairTelaInicial)
                .addGap(16, 16, 16)
                .addComponent(textoNomeEmpresaTelaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subtituloEmpresaTelaInicial)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelRoxoParteCimaLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(imagemLogoBrancaTelaInicial)
                .addGap(14, 14, 14))
        );

        PainelGrade.setBackground(new java.awt.Color(255, 255, 255));
        PainelGrade.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 51, 255), 3, true));

        imagemGrade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/imagemGradeCurricular.png"))); // NOI18N

        textoImagemGradeCurricular.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textoImagemGradeCurricular.setForeground(new java.awt.Color(153, 51, 255));
        textoImagemGradeCurricular.setText("Grade");

        textoRestoImagemGradeCurricular.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textoRestoImagemGradeCurricular.setForeground(new java.awt.Color(153, 51, 255));
        textoRestoImagemGradeCurricular.setText("Curricular");

        javax.swing.GroupLayout PainelGradeLayout = new javax.swing.GroupLayout(PainelGrade);
        PainelGrade.setLayout(PainelGradeLayout);
        PainelGradeLayout.setHorizontalGroup(
            PainelGradeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelGradeLayout.createSequentialGroup()
                .addGroup(PainelGradeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelGradeLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(imagemGrade))
                    .addGroup(PainelGradeLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(textoImagemGradeCurricular))
                    .addGroup(PainelGradeLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(textoRestoImagemGradeCurricular)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        PainelGradeLayout.setVerticalGroup(
            PainelGradeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelGradeLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(imagemGrade)
                .addGap(18, 18, 18)
                .addComponent(textoImagemGradeCurricular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoRestoImagemGradeCurricular)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        PainelGestao.setBackground(new java.awt.Color(255, 255, 255));
        PainelGestao.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 51, 255), 3, true));
        PainelGestao.setForeground(new java.awt.Color(255, 255, 255));

        imagemGestao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ImagemGestao.png"))); // NOI18N
        imagemGestao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imagemGestao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imagemGestaoMouseClicked(evt);
            }
        });

        textoImagemGestao.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textoImagemGestao.setForeground(new java.awt.Color(153, 51, 255));
        textoImagemGestao.setText("Gestão");

        javax.swing.GroupLayout PainelGestaoLayout = new javax.swing.GroupLayout(PainelGestao);
        PainelGestao.setLayout(PainelGestaoLayout);
        PainelGestaoLayout.setHorizontalGroup(
            PainelGestaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelGestaoLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(imagemGestao)
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelGestaoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(textoImagemGestao, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        PainelGestaoLayout.setVerticalGroup(
            PainelGestaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelGestaoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(imagemGestao)
                .addGap(18, 18, 18)
                .addComponent(textoImagemGestao)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        PainelMateria.setBackground(new java.awt.Color(255, 255, 255));
        PainelMateria.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 51, 255), 3, true));
        PainelMateria.setForeground(new java.awt.Color(0, 0, 0));

        imagemMateria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/imagemMateria.png"))); // NOI18N
        imagemMateria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imagemMateria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imagemMateriaMouseClicked(evt);
            }
        });

        textoImagemMateria.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textoImagemMateria.setForeground(new java.awt.Color(153, 51, 255));
        textoImagemMateria.setText("Matéria");

        javax.swing.GroupLayout PainelMateriaLayout = new javax.swing.GroupLayout(PainelMateria);
        PainelMateria.setLayout(PainelMateriaLayout);
        PainelMateriaLayout.setHorizontalGroup(
            PainelMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelMateriaLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(PainelMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoImagemMateria)
                    .addComponent(imagemMateria))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        PainelMateriaLayout.setVerticalGroup(
            PainelMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelMateriaLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(imagemMateria)
                .addGap(26, 26, 26)
                .addComponent(textoImagemMateria)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PainelTelaLayout = new javax.swing.GroupLayout(PainelTela);
        PainelTela.setLayout(PainelTelaLayout);
        PainelTelaLayout.setHorizontalGroup(
            PainelTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelRoxoParteCima, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PainelTelaLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(PainelGestao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121)
                .addComponent(PainelGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PainelMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
        );
        PainelTelaLayout.setVerticalGroup(
            PainelTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelTelaLayout.createSequentialGroup()
                .addComponent(PainelRoxoParteCima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                .addGroup(PainelTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PainelGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PainelGestao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PainelMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78))
        );

        PainelPrincipal.add(PainelTela, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoSairTelaInicialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoSairTelaInicialMouseClicked
        System.exit(0);
    }//GEN-LAST:event_botaoSairTelaInicialMouseClicked

    private void imagemMateriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imagemMateriaMouseClicked
        new TelaMateria().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_imagemMateriaMouseClicked

    private void imagemGestaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imagemGestaoMouseClicked
        new TelaGestao().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_imagemGestaoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelGestao;
    private javax.swing.JPanel PainelGrade;
    private javax.swing.JPanel PainelMateria;
    private javax.swing.JPanel PainelPrincipal;
    private javax.swing.JPanel PainelRoxoParteCima;
    private javax.swing.JPanel PainelTela;
    private javax.swing.JLabel botaoSairTelaInicial;
    private javax.swing.JLabel imagemGestao;
    private javax.swing.JLabel imagemGrade;
    private javax.swing.JLabel imagemLogoBrancaTelaInicial;
    private javax.swing.JLabel imagemMateria;
    private javax.swing.JLabel subtituloEmpresaTelaInicial;
    private javax.swing.JLabel textoImagemGestao;
    private javax.swing.JLabel textoImagemGradeCurricular;
    private javax.swing.JLabel textoImagemMateria;
    private javax.swing.JLabel textoNomeEmpresaTelaInicial;
    private javax.swing.JLabel textoRestoImagemGradeCurricular;
    // End of variables declaration//GEN-END:variables
}
